name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Docker Publish
    branches:
      - develop
    types:
      - completed

jobs:
  deploy-testnet:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Testnet
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_WORK_DIR }}
            echo ${{ secrets.PACKAGE_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            bash ./update.sh
  
  # The signet instance is maintained by the https://github.com/ckb-devrel team.
  # deploy-signet:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy Signet
  #       uses: appleboy/ssh-action@v1.0.3
  #       with:
  #         host: ${{ secrets.SSH_HOST_SIGNET }}
  #         username: ${{ secrets.SSH_USERNAME_SIGNET }}
  #         password: ${{ secrets.PASSWORD }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd ${{ secrets.SSH_WORK_DIR_SIGNET }}
  #           echo ${{ secrets.PACKAGE_TOKEN }} | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
  #           bash ./update.sh
